# SITE CONFIGURATION
title: Hanzhi Yang # your site title
author: Hanzhiyang3549 # You :P
description: > # Meta description of Homepage
  Hanzhi Yang’s Portfolio. Thoughtfully handmade product, with details that make life easier.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://HanzhiYang3549.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Hanzhi Yang
  links:
    - https://x.com/yanghanzhi79
    - https://www.instagram.com/hzyang3549
    - https://www.facebook.com/share/1P3Y1qEVWQ/?mibextid=wwXIfr
    - http://disqus.com/by/Hanzhiyang3549
    - https://github.com/HanzhiYang3549

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  An industrial designer who is passionate about exploring natural materials and immersed in the process of handcrafting products

hero_img: posts/lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: yanghanzhi79@gmail.com # email for form submission

twitter_username: yanghanzhi79 # replace with your_twitter_username or comment to remove link from footer
github_username:  HanzhiYang3549 # replace with your_github_username or comment to remove link from footer
instagram_username: hzyang3549 # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: Hanzhiyang3549 # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
